state_sa_name="tfstatemaelzayenonprod"
access_key="NiOoYWahQiC6zHIz+VSsQ+odEvaFDENMQ2pCC6IA2cuJkQAQ2kqSaHcdCc0FKrzcaLgcgKUT7hB6+AStTDfUeQ=="
container_name="akstfstate"
prefix = "escs"
private_dns_zone_name = "privatelink.westeurope.azmk8s.io"